[package]
name = "atc-recognition"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.15.3"
ringbuf = "0.4.7"
rubato = "0.16.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
thiserror = "2.0.11"
whisper-rs = { version = "0.13.2", features = ["vulkan"] }
